CREATE TABLE IF NOT EXISTS drones (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    serial_number VARCHAR(100) NOT NULL,
    model VARCHAR(50) NOT NULL,
    weight_limit DECIMAL(10, 2) NOT NULL,
    battery_capacity INT NOT NULL,
    state VARCHAR(30) NOT NULL
);


CREATE TABLE IF NOT EXISTS medications(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100) NOT NULL,
weight DECIMAL(10, 2) NOT NULL,
code VARCHAR(100) NOT NULL,
image BLOB,
drone_id INT NOT NULL,
CONSTRAINT fk_drones_medications_drone_id FOREIGN KEY (drone_id) REFERENCES drones(id) ON DELETE CASCADE
)


